### ISSUE TITLE
Test failure with PG12: psql:test/test-id.sql:28: ERROR:  column "relhasoids" does not exist

### ISSUE THREAD

**Issue by df7cb** [pgpartman/pg_partman#256]
Building with 12beta1, the tests fail:
```
16:12:42 + psql -c 'CREATE EXTENSION pgtap'
16:12:43 CREATE EXTENSION
16:12:43 + psql -c 'CREATE EXTENSION pg_partman'
16:12:43 CREATE EXTENSION
16:12:43 + pg_prove -ovf test/test-id.sql
16:12:43 psql:test/test-id.sql:28: ERROR:  column "relhasoids" does not exist
16:12:43 CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 157 at SQL statement
16:12:43 PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 612 at assignment
16:12:43 PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 DETAIL: 
16:12:43 HINT: 
16:12:43 CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 343 at RAISE
16:12:43 PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 612 at assignment
16:12:43 PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 DETAIL: 
16:12:43 HINT: 
16:12:43 CONTEXT:  PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 744 at RAISE
16:12:43 PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 test/test-id.sql .. 
16:12:43 partman, public
16:12:43 1..121
16:12:43 Dubious, test returned 3 (wstat 768, 0x300)
16:12:43 Failed 121/121 subtests 
16:12:43 
16:12:43 Test Summary Report
16:12:43 -------------------
16:12:43 test/test-id.sql (Wstat: 768 Tests: 0 Failed: 0)
16:12:43   Non-zero exit status: 3
16:12:43   Parse errors: Bad plan.  You planned 121 tests but ran 0.
16:12:43 Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.02 cusr  0.01 csys =  0.06 CPU)
16:12:43 Result: FAIL
16:12:43 *** /var/log/postgresql/postgresql-12-regress.log (last 100 lines) ***
16:12:43 2019-05-21 14:12:40.674 UTC [2837] LOG:  starting PostgreSQL 12beta1 (Debian 12~beta1-1.pgdg+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-7) 8.3.0, 64-bit
16:12:43 2019-05-21 14:12:40.675 UTC [2837] LOG:  listening on IPv6 address "::1", port 5432
16:12:43 2019-05-21 14:12:40.675 UTC [2837] LOG:  listening on IPv4 address "127.0.0.1", port 5432
16:12:43 2019-05-21 14:12:40.675 UTC [2837] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
16:12:43 2019-05-21 14:12:40.685 UTC [2838] LOG:  database system was shut down at 2019-05-21 14:12:40 UTC
16:12:43 2019-05-21 14:12:40.688 UTC [2837] LOG:  database system is ready to accept connections
16:12:43 2019-05-21 14:12:40.688 UTC [2844] LOG:  pg_partman master background worker master process initialized with role postgres
16:12:43 2019-05-21 14:12:43.483 UTC [2899] postgres@postgres ERROR:  column "relhasoids" does not exist
16:12:43 	CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 157 at SQL statement
16:12:43 	PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 612 at assignment
16:12:43 	PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 	PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 	DETAIL: 
16:12:43 	HINT: 
16:12:43 	CONTEXT: PL/pgSQL function create_partition_id(text,bigint[],boolean,boolean) line 343 at RAISE
16:12:43 	PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 612 at assignment
16:12:43 	PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 	PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 	DETAIL: 
16:12:43 	HINT: 
16:12:43 2019-05-21 14:12:43.483 UTC [2899] postgres@postgres CONTEXT:  PL/pgSQL function create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,boolean) line 744 at RAISE
16:12:43 	PL/pgSQL function results_eq(refcursor,refcursor,text) line 11 at FETCH
16:12:43 	PL/pgSQL function results_eq(text,anyarray,text) line 10 at assignment
16:12:43 2019-05-21 14:12:43.483 UTC [2899] postgres@postgres STATEMENT:  SELECT results_eq('SELECT create_parent(''partman_test.id_taptest_table'', ''col1'', ''partman'', ''10'', p_inherit_fk := false, p_jobmon := false)::text', ARRAY['true'], 'Check that create_parent() returns true');
```

**Comment by keithf4** [comment]
Thanks. Hadn't gotten around to testing in 12 yet. This one should be an easy fix at least.

**Comment by keithf4** [comment]
Just FYI, I usually wait until at least the first RC before I go fixing any new major release bugs. Just to be sure I'm fixing things in a manner that will most likely match the final version.

**Comment by keithf4** [comment]
I've resolved this issue with the `relhasoids` column and the fix will be included with my next release due sometime next week hopefully.

**Comment by keithf4** [comment]
This test failure has been fixed as of v4.2.0.

**Comment by netvoip** [comment]
I'm on 4.2.2 and PG 12.0. Still getting this error and new partition tables are not created.
